const $=id=>document.getElementById(id);
let stlVolume=null,lastResult=null;
const defaults={electricity:.25,margin:100,risk:7,maintenance:.10,handlingFee:5,minimumPrice:10,lifeHours:5000,p2sPrice:1000,p2sPower:120,h2dPrice:2200,h2dPower:160};
function settings(){try{return {...defaults,...JSON.parse(localStorage.getItem('pc3d-settings')||'{}')}}catch{return {...defaults}}}function eur(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0)}function loadSettings(){let s=settings();
Object.keys(defaults).forEach(k=>$(k).value=s[k])}function saveSettings(){let s={};
Object.keys(defaults).forEach(k=>s[k]=Number($(k).value));
localStorage.setItem('pc3d-settings',JSON.stringify(s))}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));
b.classList.add('active');
$(b.dataset.tab).classList.add('active');
if(b.dataset.tab==='history')renderHistory()});
$('settingsBtn').onclick=()=>{loadSettings();
$('settings').showModal()};
$('saveSettings').onclick=saveSettings;
$('file').onchange=async e=>{let f=e.target.files[0];
if(!f)return;
stlVolume=null;
$('fileInfo').textContent=`✓ ${f.name} — ${(f.size/1024/1024).toFixed(2)} Mo`;
let ext=f.name.split('.').pop().toLowerCase();
if(ext==='stl'){try{stlVolume=await volumeSTL(f);
let density={pla:1.24,petg:1.27,asa:1.07,tpu:1.21}[$('material').value]||1.24;
let infill=Number($('infill').value)/100;
let estimated=stlVolume*density*(.22+.78*infill);
$('grams').value=Math.max(1,estimated).toFixed(1);
$('estimateNote').textContent=`STL analysé : volume fermé ≈ ${stlVolume.toFixed(1)} cm³. Matière pré-estimée automatiquement. Le slicing automatique précis arrive à l'étape suivante.`}catch{$('estimateNote').textContent='STL détecté, mais son volume n’a pas pu être lu. Tu peux renseigner les grammes manuellement.'}}else if(ext==='gcode'){let text=await f.text();
parseGcode(text)}else{$('estimateNote').textContent='3MF importé. La lecture automatique des métadonnées Bambu sera ajoutée avec le moteur de slicing.'}};
$('material').onchange=()=>{if(stlVolume){let density={pla:1.24,petg:1.27,asa:1.07,tpu:1.21}[$('material').value];
let infill=Number($('infill').value)/100;
$('grams').value=(stlVolume*density*(.22+.78*infill)).toFixed(1)}};
$('infill').onchange=$('material').onchange;
function parseGcode(t){let grams=null,seconds=null;
for(let line of t.split(/\r?\n/)){let m=line.match(/filament used \[g\]\s*=\s*([\d.]+)/i);
if(m)grams=+m[1];
m=line.match(/estimated printing time.*?=\s*(?:(\d+)h)?\s*(?:(\d+)m)?\s*(?:(\d+)s)?/i);
if(m)seconds=(+(m[1]||0))*3600+(+(m[2]||0))*60+(+(m[3]||0))}if(grams)$('grams').value=grams.toFixed(1);
if(seconds)$('hours').value=(seconds/3600).toFixed(2);
$('estimateNote').textContent=grams||seconds?'Données détectées automatiquement dans le G-code.':'G-code importé. Certaines variantes n’exposent pas les mêmes métadonnées.'}async function volumeSTL(file){let buf=await file.arrayBuffer(),dv=new DataView(buf),tri,off,binary=false;
if(buf.byteLength>=84){tri=dv.getUint32(80,true);
binary=84+tri*50===buf.byteLength}let vol=0;
if(binary){off=84;
for(let i=0;
i<tri;
i++,off+=50){let a=[],b=[],c=[];
for(let j=0;
j<3;
j++)a.push(dv.getFloat32(off+12+j*4,true));
for(let j=0;
j<3;
j++)b.push(dv.getFloat32(off+24+j*4,true));
for(let j=0;
j<3;
j++)c.push(dv.getFloat32(off+36+j*4,true));
vol+=signed(a,b,c)}}else{let text=new TextDecoder().decode(buf),verts=[...text.matchAll(/vertex\s+([-\d.e+]+)\s+([-\d.e+]+)\s+([-\d.e+]+)/ig)].map(m=>[+m[1],+m[2],+m[3]]);
for(let i=0;
i+2<verts.length;
i+=3)vol+=signed(verts[i],verts[i+1],verts[i+2])}return Math.abs(vol)/1000}function signed(a,b,c){return (a[0]*(b[1]*c[2]-b[2]*c[1])-a[1]*(b[0]*c[2]-b[2]*c[0])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6}function calculatePrice({s,machine,h,g,q,spoolPrice,spoolWeight}){let material=g*(spoolPrice/(spoolWeight||1000))*q,power=(machine==='p2s'?s.p2sPower:s.h2dPower)/1000*h*s.electricity*q,machineCost=(machine==='p2s'?s.p2sPrice:s.h2dPrice)/s.lifeHours*h*q,maint=s.maintenance*h*q,base=material+power+machineCost+maint,risk=base*s.risk/100,total=base+risk,marginAmount=total*s.margin/100,subtotal=total+marginAmount+s.handlingFee,sale=Math.max(s.minimumPrice,subtotal),minimumAdjustment=sale-subtotal,profit=sale-total;
return{material,power,machineCost,maint,risk,total,marginAmount,handlingFee:s.handlingFee,minimumAdjustment,sale,profit}}$('calcBtn').onclick=()=>{let s=settings(),machine=$('printer').value,h=+$('hours').value||0,g=+$('grams').value||0,q=Math.max(1,+$('qty').value||1),price=calculatePrice({s,machine,h,g,q,spoolPrice:+$('spoolPrice').value,spoolWeight:+$('spoolWeight').value}),{material,power,machineCost,maint,risk,total,marginAmount,handlingFee,minimumAdjustment,sale,profit}=price;
lastResult={date:new Date().toISOString(),file:$('file').files[0]?.name||'Calcul manuel',machine,grams:g,hours:h,total,sale,profit,handlingFee,minimumAdjustment};
$('cMaterial').textContent=eur(material);
$('cPower').textContent=eur(power);
$('cMachine').textContent=eur(machineCost);
$('cMaint').textContent=eur(maint);
$('cRisk').textContent=eur(risk);
$('cTotal').textContent=eur(total);
$('cMargin').textContent=eur(marginAmount);
$('cHandling').textContent=eur(handlingFee);
$('cMinimum').textContent=minimumAdjustment>0?`+ ${eur(minimumAdjustment)}`:'Non appliqué';
$('cMinimumRow').classList.toggle('muted',minimumAdjustment<=0);
$('salePrice').textContent=eur(sale);
$('profit').textContent=eur(profit);
$('result').classList.remove('hidden');
$('result').scrollIntoView({behavior:'smooth'})};
$('saveBtn').onclick=()=>{if(!lastResult)return;
let h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');
h.unshift(lastResult);
localStorage.setItem('pc3d-history',JSON.stringify(h.slice(0,100)));
$('saveBtn').textContent='✓ Enregistré'};
function renderHistory(){let h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');
$('historyList').innerHTML=h.length?h.map(x=>`<div class='historyItem'><b>${eur(x.sale)}</b><strong>${x.file}</strong><small>${x.machine.toUpperCase()} · ${x.grams} g · ${x.hours.toFixed(2)} h · coût ${eur(x.total)}</small></div>`).join(''):`<div class='card'>Aucun calcul enregistré pour le moment.</div>`}$('clearHistory').onclick=()=>{if(confirm('Effacer tout l’historique ?')){localStorage.removeItem('pc3d-history');
renderHistory()}};
loadSettings();
