const $ = id => document.getElementById(id);
let selectedFile = null, lastResult = null;
const defaults = {electricity:.25,margin:100,risk:7,maintenance:.10,handlingFee:5,minimumPrice:10,lifeHours:5000,p2sPrice:1000,p2sPower:120,h2dPrice:2200,h2dPower:160};
function settings(){try{return {...defaults,...JSON.parse(localStorage.getItem('pc3d-settings')||'{}')}}catch{return {...defaults}}}
function eur(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0)}
function loadSettings(){const s=settings();Object.keys(defaults).forEach(k=>$(k).value=s[k])}
function saveSettings(){const s={};Object.keys(defaults).forEach(k=>s[k]=Number($(k).value));localStorage.setItem('pc3d-settings',JSON.stringify(s))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='history')renderHistory()});
$('settingsBtn').onclick=()=>{loadSettings();$('settings').showModal()};$('saveSettings').onclick=saveSettings;
function formatDuration(seconds){const h=Math.floor(seconds/3600),m=Math.round((seconds%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
$('file').onchange=e=>{selectedFile=e.target.files[0]||null;if(!selectedFile)return;$('fileInfo').textContent=`✓ ${selectedFile.name} — ${(selectedFile.size/1024/1024).toFixed(2)} Mo`;$('estimateNote').textContent='Fichier ajouté. Recopie maintenant le temps et les grammes indiqués par Bambu Studio.'};
function calculatePrice({s,machine,h,g,q,spoolPrice,spoolWeight}){const material=g*(spoolPrice/(spoolWeight||1000))*q,power=(machine==='p2s'?s.p2sPower:s.h2dPower)/1000*h*s.electricity*q,machineCost=(machine==='p2s'?s.p2sPrice:s.h2dPrice)/s.lifeHours*h*q,maint=s.maintenance*h*q,base=material+power+machineCost+maint,risk=base*s.risk/100,total=base+risk,marginAmount=total*s.margin/100,subtotal=total+marginAmount+s.handlingFee,sale=Math.max(s.minimumPrice,subtotal),minimumAdjustment=sale-subtotal,profit=sale-total;return{material,power,machineCost,maint,risk,total,marginAmount,handlingFee:s.handlingFee,minimumAdjustment,sale,profit}}
function calculateAndDisplay(){const h=+$('hours').value||0,g=+$('grams').value||0;if(h<=0||g<=0){$('estimateNote').textContent='Renseigne le temps d’impression et les grammes de filament pour calculer le prix.';return}const s=settings(),machine=$('printer').value,q=Math.max(1,+$('qty').value||1),price=calculatePrice({s,machine,h,g,q,spoolPrice:+$('spoolPrice').value,spoolWeight:+$('spoolWeight').value}),{material,power,machineCost,maint,risk,total,marginAmount,handlingFee,minimumAdjustment,sale,profit}=price;lastResult={date:new Date().toISOString(),file:selectedFile?.name||'Calcul manuel',machine,material:$('material').value,grams:g,hours:h,filamentLengthMm:0,supports:$('supports').checked,total,sale,profit,handlingFee,minimumAdjustment};$('cMaterial').textContent=eur(material);$('cPower').textContent=eur(power);$('cMachine').textContent=eur(machineCost);$('cMaint').textContent=eur(maint);$('cRisk').textContent=eur(risk);$('cTotal').textContent=eur(total);$('cMargin').textContent=eur(marginAmount);$('cHandling').textContent=eur(handlingFee);$('cMinimum').textContent=minimumAdjustment>0?`+ ${eur(minimumAdjustment)}`:'Non appliqué';$('cMinimumRow').classList.toggle('muted',minimumAdjustment<=0);$('salePrice').textContent=eur(sale);$('profit').textContent=eur(profit);$('result').classList.remove('hidden')}
$('calcBtn').onclick=calculateAndDisplay;$('qty').onchange=()=>{if(+$('hours').value>0&&+$('grams').value>0)calculateAndDisplay()};$('spoolPrice').onchange=$('qty').onchange;$('spoolWeight').onchange=$('qty').onchange;
$('saveBtn').onclick=()=>{if(!lastResult)return;const h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');h.unshift(lastResult);localStorage.setItem('pc3d-history',JSON.stringify(h.slice(0,100)));$('saveBtn').textContent='✓ Enregistré'};
function renderHistory(){const h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');$('historyList').innerHTML=h.length?h.map(x=>`<div class='historyItem'><b>${eur(x.sale)}</b><strong>${x.file}</strong><small>${x.machine.toUpperCase()} · ${(x.material||'').toUpperCase()} · ${x.grams.toFixed(1)} g · ${formatDuration(Math.round(x.hours*3600))} · coût ${eur(x.total)}</small></div>`).join(''):`<div class='card'>Aucun calcul enregistré pour le moment.</div>`}
$('clearHistory').onclick=()=>{if(confirm('Effacer tout l’historique ?')){localStorage.removeItem('pc3d-history');renderHistory()}};loadSettings();
