const $ = id => document.getElementById(id);
const SLICER_URL = 'http://127.0.0.1:48921';
let selectedFile = null, sliceResult = null, lastResult = null, sliceTimer = null, slicerAvailable = false, stlVolume = null;
const defaults = {electricity:.25,margin:100,risk:7,maintenance:.10,handlingFee:5,minimumPrice:10,lifeHours:5000,p2sPrice:1000,p2sPower:120,h2dPrice:2200,h2dPower:160};
function settings(){try{return {...defaults,...JSON.parse(localStorage.getItem('pc3d-settings')||'{}')}}catch{return {...defaults}}}
function eur(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0)}
function loadSettings(){const s=settings();Object.keys(defaults).forEach(k=>$(k).value=s[k])}
function saveSettings(){const s={};Object.keys(defaults).forEach(k=>s[k]=Number($(k).value));localStorage.setItem('pc3d-settings',JSON.stringify(s))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='history')renderHistory()});
$('settingsBtn').onclick=()=>{loadSettings();$('settings').showModal()};$('saveSettings').onclick=saveSettings;
async function checkSlicer(){try{const response=await fetch(`${SLICER_URL}/health`,{signal:AbortSignal.timeout(1200)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error);slicerAvailable=true;$('slicerState').className='slicerState ready';$('slicerState').textContent='● Calcul précis Bambu Studio disponible';return true}catch{slicerAvailable=false;$('slicerState').className='slicerState ready';$('slicerState').textContent='● Mode autonome actif';return false}}
async function sliceFile(){if(!selectedFile)return;if(!slicerAvailable){await estimateLocally();return}sliceResult=null;$('sliceProgress').classList.remove('hidden');$('estimateNote').textContent='Calcul précis en cours avec Bambu Studio…';const form=new FormData();form.append('file',selectedFile);form.append('machine',$('printer').value);form.append('material',$('material').value);form.append('supports',$('supports').checked);form.append('infill',$('infill').value);try{const response=await fetch(`${SLICER_URL}/slice`,{method:'POST',body:form}),data=await response.json();if(!response.ok)throw new Error(data.error||'Échec du slicing');sliceResult=data;$('hours').value=data.hours.toFixed(2);$('grams').value=data.grams.toFixed(1);$('filamentLength').textContent=`${(data.filamentLengthMm/1000).toFixed(2)} m`;$('supportDetected').textContent=data.supports?'Oui':'Non';$('sliceSource').textContent=data.source;$('estimateNote').textContent=`✓ Calcul précis terminé : ${formatDuration(data.seconds)}, ${data.grams.toFixed(1)} g.`;calculateAndDisplay()}catch{await checkSlicer();await estimateLocally()}finally{$('sliceProgress').classList.add('hidden')}}
async function estimateLocally(){sliceResult=null;const ext=selectedFile.name.split('.').pop().toLowerCase();if(ext==='stl'){try{stlVolume=await volumeSTL(selectedFile);updateEstimatedGrams();$('sliceSource').textContent='Estimation locale du STL';$('supportDetected').textContent=$('supports').checked?'À inclure':'Non';$('filamentLength').textContent='—';$('estimateNote').textContent=`✓ STL analysé dans le navigateur. Poids pré-estimé : ${$('grams').value} g. Renseigne le temps indiqué par Bambu Studio, puis calcule le prix.`}catch{$('estimateNote').textContent='STL importé. Renseigne le temps et les grammes pour calculer le prix.'}}else{$('estimateNote').textContent='3MF importé. Renseigne le temps et les grammes indiqués par Bambu Studio pour calculer le prix.'}}
function updateEstimatedGrams(){if(!stlVolume)return;const density={pla:1.24,petg:1.27,asa:1.07,tpu:1.21}[$('material').value]||1.24,infill=Number($('infill').value)/100,estimated=stlVolume*density*(.22+.78*infill)*($('supports').checked?1.12:1);$('grams').value=Math.max(1,estimated).toFixed(1)}
async function volumeSTL(file){const buf=await file.arrayBuffer(),dv=new DataView(buf);let tri,off,binary=false,vol=0;if(buf.byteLength>=84){tri=dv.getUint32(80,true);binary=84+tri*50===buf.byteLength}if(binary){off=84;for(let i=0;i<tri;i++,off+=50){const a=[],b=[],c=[];for(let j=0;j<3;j++)a.push(dv.getFloat32(off+12+j*4,true));for(let j=0;j<3;j++)b.push(dv.getFloat32(off+24+j*4,true));for(let j=0;j<3;j++)c.push(dv.getFloat32(off+36+j*4,true));vol+=signed(a,b,c)}}else{const text=await file.text(),verts=[...text.matchAll(/vertex\s+([-\d.e+]+)\s+([-\d.e+]+)\s+([-\d.e+]+)/ig)].map(m=>[+m[1],+m[2],+m[3]]);for(let i=0;i+2<verts.length;i+=3)vol+=signed(verts[i],verts[i+1],verts[i+2])}return Math.abs(vol)/1000}
function signed(a,b,c){return(a[0]*(b[1]*c[2]-b[2]*c[1])-a[1]*(b[0]*c[2]-b[2]*c[0])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6}
function formatDuration(seconds){const h=Math.floor(seconds/3600),m=Math.round((seconds%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
$('file').onchange=e=>{selectedFile=e.target.files[0]||null;if(!selectedFile)return;sliceResult=null;stlVolume=null;$('fileInfo').textContent=`✓ ${selectedFile.name} — ${(selectedFile.size/1024/1024).toFixed(2)} Mo`;sliceFile()};
['printer','material','supports','infill'].forEach(id=>$(id).onchange=()=>{if(stlVolume&&!slicerAvailable){updateEstimatedGrams();return}if(!selectedFile||!slicerAvailable)return;clearTimeout(sliceTimer);sliceTimer=setTimeout(sliceFile,250)});$('retrySlice').onclick=async()=>{await checkSlicer();if(selectedFile)sliceFile()};
function calculatePrice({s,machine,h,g,q,spoolPrice,spoolWeight}){const material=g*(spoolPrice/(spoolWeight||1000))*q,power=(machine==='p2s'?s.p2sPower:s.h2dPower)/1000*h*s.electricity*q,machineCost=(machine==='p2s'?s.p2sPrice:s.h2dPrice)/s.lifeHours*h*q,maint=s.maintenance*h*q,base=material+power+machineCost+maint,risk=base*s.risk/100,total=base+risk,marginAmount=total*s.margin/100,subtotal=total+marginAmount+s.handlingFee,sale=Math.max(s.minimumPrice,subtotal),minimumAdjustment=sale-subtotal,profit=sale-total;return{material,power,machineCost,maint,risk,total,marginAmount,handlingFee:s.handlingFee,minimumAdjustment,sale,profit}}
function calculateAndDisplay(){const h=+$('hours').value||0,g=+$('grams').value||0;if(h<=0||g<=0){$('estimateNote').textContent='Renseigne le temps d’impression et les grammes de filament pour calculer le prix.';return}const s=settings(),machine=$('printer').value,q=Math.max(1,+$('qty').value||1),price=calculatePrice({s,machine,h,g,q,spoolPrice:+$('spoolPrice').value,spoolWeight:+$('spoolWeight').value}),{material,power,machineCost,maint,risk,total,marginAmount,handlingFee,minimumAdjustment,sale,profit}=price;lastResult={date:new Date().toISOString(),file:selectedFile?.name||'Calcul manuel',machine,material:$('material').value,grams:g,hours:h,filamentLengthMm:sliceResult?.filamentLengthMm||0,supports:sliceResult?.supports||$('supports').checked,total,sale,profit,handlingFee,minimumAdjustment};$('cMaterial').textContent=eur(material);$('cPower').textContent=eur(power);$('cMachine').textContent=eur(machineCost);$('cMaint').textContent=eur(maint);$('cRisk').textContent=eur(risk);$('cTotal').textContent=eur(total);$('cMargin').textContent=eur(marginAmount);$('cHandling').textContent=eur(handlingFee);$('cMinimum').textContent=minimumAdjustment>0?`+ ${eur(minimumAdjustment)}`:'Non appliqué';$('cMinimumRow').classList.toggle('muted',minimumAdjustment<=0);$('salePrice').textContent=eur(sale);$('profit').textContent=eur(profit);$('result').classList.remove('hidden')}
$('calcBtn').onclick=calculateAndDisplay;$('qty').onchange=()=>{if(sliceResult)calculateAndDisplay()};$('spoolPrice').onchange=$('qty').onchange;$('spoolWeight').onchange=$('qty').onchange;
$('saveBtn').onclick=()=>{if(!lastResult)return;const h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');h.unshift(lastResult);localStorage.setItem('pc3d-history',JSON.stringify(h.slice(0,100)));$('saveBtn').textContent='✓ Enregistré'};
function renderHistory(){const h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');$('historyList').innerHTML=h.length?h.map(x=>`<div class='historyItem'><b>${eur(x.sale)}</b><strong>${x.file}</strong><small>${x.machine.toUpperCase()} · ${(x.material||'').toUpperCase()} · ${x.grams.toFixed(1)} g · ${formatDuration(Math.round(x.hours*3600))} · coût ${eur(x.total)}</small></div>`).join(''):`<div class='card'>Aucun calcul enregistré pour le moment.</div>`}
$('clearHistory').onclick=()=>{if(confirm('Effacer tout l’historique ?')){localStorage.removeItem('pc3d-history');renderHistory()}};loadSettings();checkSlicer();
