const $ = id => document.getElementById(id);
const SLICER_URL = 'http://127.0.0.1:48921';
let selectedFile = null, sliceResult = null, lastResult = null, sliceTimer = null;
const defaults = {electricity:.25,margin:100,risk:7,maintenance:.10,handlingFee:5,minimumPrice:10,lifeHours:5000,p2sPrice:1000,p2sPower:120,h2dPrice:2200,h2dPower:160};
function settings(){try{return {...defaults,...JSON.parse(localStorage.getItem('pc3d-settings')||'{}')}}catch{return {...defaults}}}
function eur(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0)}
function loadSettings(){const s=settings();Object.keys(defaults).forEach(k=>$(k).value=s[k])}
function saveSettings(){const s={};Object.keys(defaults).forEach(k=>s[k]=Number($(k).value));localStorage.setItem('pc3d-settings',JSON.stringify(s))}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='history')renderHistory()});
$('settingsBtn').onclick=()=>{loadSettings();$('settings').showModal()};$('saveSettings').onclick=saveSettings;
async function checkSlicer(){try{const response=await fetch(`${SLICER_URL}/health`,{signal:AbortSignal.timeout(1800)}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error);$('slicerState').className='slicerState ready';$('slicerState').textContent='● Moteur Bambu Studio prêt';return true}catch{$('slicerState').className='slicerState offline';$('slicerState').textContent='● Compagnon de slicing non démarré';return false}}
async function sliceFile(){if(!selectedFile)return;sliceResult=null;$('calcBtn').disabled=true;$('sliceProgress').classList.remove('hidden');$('estimateNote').textContent='Tranchage réel en cours avec Bambu Studio…';const form=new FormData();form.append('file',selectedFile);form.append('machine',$('printer').value);form.append('material',$('material').value);form.append('supports',$('supports').checked);form.append('infill',$('infill').value);try{const response=await fetch(`${SLICER_URL}/slice`,{method:'POST',body:form}),data=await response.json();if(!response.ok)throw new Error(data.error||'Échec du slicing');sliceResult=data;$('hours').value=data.hours.toFixed(2);$('grams').value=data.grams.toFixed(1);$('filamentLength').textContent=`${(data.filamentLengthMm/1000).toFixed(2)} m`;$('supportDetected').textContent=data.supports?'Oui':'Non';$('sliceSource').textContent=data.source;$('estimateNote').textContent=`✓ Calcul réel terminé : ${formatDuration(data.seconds)}, ${data.grams.toFixed(1)} g de filament.`;$('calcBtn').disabled=false;calculateAndDisplay()}catch(error){$('hours').value='';$('grams').value='';$('estimateNote').textContent=`Impossible de trancher : ${error.message}. Démarre le compagnon local puis réessaie.`;await checkSlicer()}finally{$('sliceProgress').classList.add('hidden')}}
function formatDuration(seconds){const h=Math.floor(seconds/3600),m=Math.round((seconds%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
$('file').onchange=e=>{selectedFile=e.target.files[0]||null;if(!selectedFile)return;sliceResult=null;$('fileInfo').textContent=`✓ ${selectedFile.name} — ${(selectedFile.size/1024/1024).toFixed(2)} Mo`;sliceFile()};
['printer','material','supports','infill'].forEach(id=>$(id).onchange=()=>{if(!selectedFile)return;clearTimeout(sliceTimer);sliceTimer=setTimeout(sliceFile,250)});$('retrySlice').onclick=()=>sliceFile();
function calculatePrice({s,machine,h,g,q,spoolPrice,spoolWeight}){const material=g*(spoolPrice/(spoolWeight||1000))*q,power=(machine==='p2s'?s.p2sPower:s.h2dPower)/1000*h*s.electricity*q,machineCost=(machine==='p2s'?s.p2sPrice:s.h2dPrice)/s.lifeHours*h*q,maint=s.maintenance*h*q,base=material+power+machineCost+maint,risk=base*s.risk/100,total=base+risk,marginAmount=total*s.margin/100,subtotal=total+marginAmount+s.handlingFee,sale=Math.max(s.minimumPrice,subtotal),minimumAdjustment=sale-subtotal,profit=sale-total;return{material,power,machineCost,maint,risk,total,marginAmount,handlingFee:s.handlingFee,minimumAdjustment,sale,profit}}
function calculateAndDisplay(){if(!sliceResult){$('estimateNote').textContent='Importe puis tranche un fichier STL ou 3MF avant de calculer.';return}const s=settings(),machine=$('printer').value,h=sliceResult.hours,g=sliceResult.grams,q=Math.max(1,+$('qty').value||1),price=calculatePrice({s,machine,h,g,q,spoolPrice:+$('spoolPrice').value,spoolWeight:+$('spoolWeight').value}),{material,power,machineCost,maint,risk,total,marginAmount,handlingFee,minimumAdjustment,sale,profit}=price;lastResult={date:new Date().toISOString(),file:selectedFile?.name||'Fichier',machine,material:$('material').value,grams:g,hours:h,filamentLengthMm:sliceResult.filamentLengthMm,supports:sliceResult.supports,total,sale,profit,handlingFee,minimumAdjustment};$('cMaterial').textContent=eur(material);$('cPower').textContent=eur(power);$('cMachine').textContent=eur(machineCost);$('cMaint').textContent=eur(maint);$('cRisk').textContent=eur(risk);$('cTotal').textContent=eur(total);$('cMargin').textContent=eur(marginAmount);$('cHandling').textContent=eur(handlingFee);$('cMinimum').textContent=minimumAdjustment>0?`+ ${eur(minimumAdjustment)}`:'Non appliqué';$('cMinimumRow').classList.toggle('muted',minimumAdjustment<=0);$('salePrice').textContent=eur(sale);$('profit').textContent=eur(profit);$('result').classList.remove('hidden')}
$('calcBtn').onclick=calculateAndDisplay;$('qty').onchange=()=>{if(sliceResult)calculateAndDisplay()};$('spoolPrice').onchange=$('qty').onchange;$('spoolWeight').onchange=$('qty').onchange;
$('saveBtn').onclick=()=>{if(!lastResult)return;const h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');h.unshift(lastResult);localStorage.setItem('pc3d-history',JSON.stringify(h.slice(0,100)));$('saveBtn').textContent='✓ Enregistré'};
function renderHistory(){const h=JSON.parse(localStorage.getItem('pc3d-history')||'[]');$('historyList').innerHTML=h.length?h.map(x=>`<div class='historyItem'><b>${eur(x.sale)}</b><strong>${x.file}</strong><small>${x.machine.toUpperCase()} · ${(x.material||'').toUpperCase()} · ${x.grams.toFixed(1)} g · ${formatDuration(Math.round(x.hours*3600))} · coût ${eur(x.total)}</small></div>`).join(''):`<div class='card'>Aucun calcul enregistré pour le moment.</div>`}
$('clearHistory').onclick=()=>{if(confirm('Effacer tout l’historique ?')){localStorage.removeItem('pc3d-history');renderHistory()}};loadSettings();checkSlicer();
